import { prisma } from "../src/config/prisma.js";

async function main() {
    await prisma.$executeRawUnsafe("ALTER TABLE transactions ADD COLUMN IF NOT EXISTS paid_amount REAL");
    await prisma.$executeRawUnsafe(
        "CREATE TABLE IF NOT EXISTS transaction_items (transaction_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, transaction_id BIGINT NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE, product_name TEXT NOT NULL, category TEXT, quantity REAL NOT NULL, unit TEXT, price_per_unit REAL, line_total REAL NOT NULL, created_at TIMESTAMP(0) NOT NULL DEFAULT NOW())"
    );
    await prisma.$executeRawUnsafe(
        "CREATE INDEX IF NOT EXISTS idx_transaction_items_transaction_id ON transaction_items(transaction_id)"
    );

    console.log("Applied additive transaction migration.");
}

main()
    .catch((error) => {
        console.error("Failed to apply additive transaction migration", error);
        process.exitCode = 1;
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
