begin;

create table if not exists public.business_operating_status (
    business_id bigint primary key references public.business(business_id) on delete cascade,
    stall_number text not null,
    is_open boolean not null default false,
    updated_at timestamptz not null default now(),
    updated_by_account_id bigint references public.accounts(account_id) on delete set null
);

create table if not exists public.business_operating_status_history (
    history_id bigint generated by default as identity primary key,
    business_id bigint not null references public.business(business_id) on delete cascade,
    stall_number text not null,
    previous_is_open boolean not null,
    is_open boolean not null,
    changed_at timestamptz not null default now(),
    changed_by_account_id bigint references public.accounts(account_id) on delete set null
);

create index if not exists business_operating_status_history_business_changed_idx
    on public.business_operating_status_history (business_id, changed_at desc);

insert into public.business_operating_status (business_id, stall_number, is_open)
select b.business_id, coalesce(b.stall_number, b.stall_no), true
from public.business b
on conflict (business_id) do nothing;

create or replace function public.initialize_business_operating_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.business_operating_status (business_id, stall_number, is_open)
    values (new.business_id, coalesce(new.stall_number, new.stall_no), false)
    on conflict (business_id) do update
    set stall_number = excluded.stall_number
    where public.business_operating_status.stall_number is distinct from excluded.stall_number;
    return new;
end;
$$;

drop trigger if exists initialize_business_operating_status_after_insert on public.business;
create trigger initialize_business_operating_status_after_insert
after insert on public.business
for each row execute function public.initialize_business_operating_status();

drop trigger if exists synchronize_business_operating_stall_after_update on public.business;
create trigger synchronize_business_operating_stall_after_update
after update of stall_number, stall_no on public.business
for each row execute function public.initialize_business_operating_status();

create or replace function public.audit_business_operating_status_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if old.is_open is distinct from new.is_open then
        insert into public.business_operating_status_history (
            business_id, stall_number, previous_is_open, is_open, changed_by_account_id
        ) values (
            new.business_id, new.stall_number, old.is_open, new.is_open, new.updated_by_account_id
        );
    end if;
    return new;
end;
$$;

drop trigger if exists audit_business_operating_status_after_update on public.business_operating_status;
create trigger audit_business_operating_status_after_update
after update on public.business_operating_status
for each row execute function public.audit_business_operating_status_change();

create or replace function public.current_pos_account_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
    select a.account_id
    from public.accounts a
    where a.auth_user_id = auth.uid()
      and lower(coalesce(a.status::text, '')) = 'active'
      and coalesce(a.is_verified, false) = true
    limit 1
$$;

create or replace function public.can_read_business_operating_status(p_business_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.accounts a
        left join public.business_owner bo on bo.account_id = a.account_id
        left join public.vendor v on v.account_id = a.account_id
        join public.business b on b.business_id = p_business_id
        where a.auth_user_id = auth.uid()
          and lower(coalesce(a.status::text, '')) = 'active'
          and coalesce(a.is_verified, false) = true
          and (
              (bo.business_owner_id = b.business_owner_id and bo.archived_at is null)
              or (
                  v.business_owner_id = b.business_owner_id
                  and coalesce(v.is_approved, false) = true
              )
              or lower(a.user_type::text) = 'developer'
          )
    )
$$;

create or replace function public.can_manage_business_operating_status(p_business_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
        from public.accounts a
        left join public.business_owner bo on bo.account_id = a.account_id
        left join public.vendor v on v.account_id = a.account_id
        join public.business b on b.business_id = p_business_id
        where a.auth_user_id = auth.uid()
          and lower(coalesce(a.status::text, '')) = 'active'
          and coalesce(a.is_verified, false) = true
          and (
              (bo.business_owner_id = b.business_owner_id and bo.archived_at is null)
              or (
                  v.business_owner_id = b.business_owner_id
                  and coalesce(v.is_approved, false) = true
              )
          )
    )
$$;

alter table public.business_operating_status enable row level security;
alter table public.business_operating_status_history enable row level security;

drop policy if exists "Authorized accounts can read operating status" on public.business_operating_status;
create policy "Authorized accounts can read operating status"
on public.business_operating_status for select
to authenticated
using (public.can_read_business_operating_status(business_id));

drop policy if exists "Authorized accounts can read operating history" on public.business_operating_status_history;
create policy "Authorized accounts can read operating history"
on public.business_operating_status_history for select
to authenticated
using (public.can_read_business_operating_status(business_id));

revoke all on public.business_operating_status from anon, authenticated;
revoke all on public.business_operating_status_history from anon, authenticated;
grant select on public.business_operating_status to authenticated;
grant select on public.business_operating_status_history to authenticated;

create or replace function public.get_business_operating_status(p_business_id bigint)
returns table (
    business_id bigint,
    stall_number text,
    is_open boolean,
    updated_at timestamptz,
    updated_by_account_id bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null or not public.can_read_business_operating_status(p_business_id) then
        raise exception 'OPERATING_STATUS_FORBIDDEN: You are not authorized to view this business.' using errcode = '42501';
    end if;

    return query
    select s.business_id, s.stall_number, s.is_open, s.updated_at, s.updated_by_account_id
    from public.business_operating_status s
    where s.business_id = p_business_id;
end;
$$;

create or replace function public.set_business_operating_status(p_business_id bigint, p_is_open boolean)
returns table (
    business_id bigint,
    stall_number text,
    is_open boolean,
    updated_at timestamptz,
    updated_by_account_id bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_status public.business_operating_status%rowtype;
    v_account_id bigint;
begin
    if auth.uid() is null or not public.can_manage_business_operating_status(p_business_id) then
        raise exception 'OPERATING_STATUS_FORBIDDEN: Only the owner or approved personnel can change this status.' using errcode = '42501';
    end if;

    v_account_id := public.current_pos_account_id();

    insert into public.business_operating_status (business_id, stall_number, is_open)
    select b.business_id, coalesce(b.stall_number, b.stall_no), false
    from public.business b
    where b.business_id = p_business_id
    on conflict (business_id) do nothing;

    select * into v_status
    from public.business_operating_status s
    where s.business_id = p_business_id
    for update;

    if not found then
        raise exception 'OPERATING_STATUS_NOT_FOUND: Business status was not found.' using errcode = 'P0002';
    end if;

    if v_status.is_open is distinct from p_is_open then
        update public.business_operating_status s
        set is_open = p_is_open,
            updated_at = now(),
            updated_by_account_id = v_account_id
        where s.business_id = p_business_id
        returning * into v_status;

    end if;

    return query
    select v_status.business_id, v_status.stall_number, v_status.is_open,
           v_status.updated_at, v_status.updated_by_account_id;
end;
$$;

alter table public.sales_transaction
    add column if not exists business_id bigint references public.business(business_id) on delete restrict;

create index if not exists sales_transaction_business_id_idx
    on public.sales_transaction (business_id);

create or replace function public.reject_sale_when_business_closed()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_business_id bigint;
    v_stall_id public.business.stall_id%type;
    v_stall_number text;
    v_is_open boolean;
begin
    v_business_id := new.business_id;

    if v_business_id is null then
        select b.business_id
        into v_business_id
        from public.business b
        where (new.stall_id is not null and b.stall_id::text = new.stall_id::text)
           or (new.stall_number is not null and coalesce(b.stall_number, b.stall_no) = new.stall_number)
        order by b.business_id desc
        limit 1;
    end if;

    if v_business_id is null then
        raise exception 'SALE_BUSINESS_REQUIRED: The sale could not be matched to a business.' using errcode = '23514';
    end if;

    select b.stall_id, coalesce(b.stall_number, b.stall_no)
    into v_stall_id, v_stall_number
    from public.business b
    where b.business_id = v_business_id;

    if not found then
        raise exception 'SALE_BUSINESS_REQUIRED: The selected business does not exist.' using errcode = '23503';
    end if;

    if new.stall_id is not null and v_stall_id is not null and new.stall_id <> v_stall_id then
        raise exception 'SALE_STALL_MISMATCH: The sale stall does not belong to the selected business.' using errcode = '23514';
    end if;

    if new.stall_number is not null and v_stall_number is not null and new.stall_number <> v_stall_number then
        raise exception 'SALE_STALL_MISMATCH: The sale stall number does not belong to the selected business.' using errcode = '23514';
    end if;

    select s.is_open
    into v_is_open
    from public.business_operating_status s
    where s.business_id = v_business_id
    for share;

    if not found or not coalesce(v_is_open, false) then
        raise exception 'STALL_CLOSED: Open the stall before starting a sale.' using errcode = 'P0001';
    end if;

    new.business_id := v_business_id;
    new.stall_id := coalesce(v_stall_id, new.stall_id);
    new.stall_number := coalesce(v_stall_number, new.stall_number);
    return new;
end;
$$;

drop trigger if exists reject_sale_when_business_closed_before_insert on public.sales_transaction;
create trigger reject_sale_when_business_closed_before_insert
before insert on public.sales_transaction
for each row execute function public.reject_sale_when_business_closed();

create or replace function public.record_open_stall_sale(p_business_id bigint, p_rows jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_account_id bigint;
    v_stall_id public.business.stall_id%type;
    v_stall_number text;
    v_is_open boolean;
begin
    if auth.uid() is null or not public.can_manage_business_operating_status(p_business_id) then
        raise exception 'SALE_FORBIDDEN: Only the owner or approved personnel can record sales.' using errcode = '42501';
    end if;

    if p_rows is null or jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
        raise exception 'SALE_ROWS_REQUIRED: At least one sale row is required.' using errcode = '22023';
    end if;

    v_account_id := public.current_pos_account_id();

    select b.stall_id, coalesce(b.stall_number, b.stall_no)
    into v_stall_id, v_stall_number
    from public.business b
    where b.business_id = p_business_id;

    if not found then
        raise exception 'SALE_BUSINESS_REQUIRED: The selected business does not exist.' using errcode = '23503';
    end if;

    select s.is_open
    into v_is_open
    from public.business_operating_status s
    where s.business_id = p_business_id
    for share;

    if not found or not coalesce(v_is_open, false) then
        raise exception 'STALL_CLOSED: Open the stall before starting a sale.' using errcode = 'P0001';
    end if;

    insert into public.sales_transaction (
        business_id, stall_id, stall_number, account_id, username, category, product,
        product_listing_id, catalog_product_id, quantity_sold_kg, sold_quantity,
        sold_unit, unit_price_php, transaction_date, sync_date
    )
    select
        p_business_id,
        v_stall_id,
        v_stall_number,
        v_account_id,
        coalesce(r.username, ''),
        r.category,
        r.product,
        r.product_listing_id,
        r.catalog_product_id,
        r.quantity_sold_kg,
        coalesce(r.sold_quantity, r.quantity_sold_kg),
        r.sold_unit,
        r.unit_price_php,
        coalesce(r.transaction_date, now()),
        coalesce(r.sync_date, now())
    from jsonb_to_recordset(p_rows) as r(
        username text,
        category text,
        product text,
        product_listing_id text,
        catalog_product_id uuid,
        quantity_sold_kg numeric,
        sold_quantity numeric,
        sold_unit text,
        unit_price_php numeric,
        transaction_date timestamptz,
        sync_date timestamptz
    );
end;
$$;

revoke all on function public.get_business_operating_status(bigint) from public;
revoke all on function public.set_business_operating_status(bigint, boolean) from public;
revoke all on function public.record_open_stall_sale(bigint, jsonb) from public;
grant execute on function public.get_business_operating_status(bigint) to authenticated;
grant execute on function public.set_business_operating_status(bigint, boolean) to authenticated;
grant execute on function public.record_open_stall_sale(bigint, jsonb) to authenticated;

do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'business_operating_status'
    ) then
        alter publication supabase_realtime add table public.business_operating_status;
    end if;
end;
$$;

commit;
